import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:pleyo_tablet_app/consts/colors.dart';
import 'package:pleyo_tablet_app/consts/text_styles.dart';
import 'package:pleyo_tablet_app/pages/single_player_mode/presentation/controllers/single_player_mode_controller.dart';
import 'package:pleyo_tablet_app/routes/app_pages.dart';
import 'package:pleyo_tablet_app/widgets/custom_text.dart';
import 'package:pleyo_tablet_app/widgets/custom_text_field.dart';

class PlayerNameStep extends GetView<SinglePlayerModeController> {
  const PlayerNameStep({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          backgroundColor: const Color(ColorCode.primaryBackground),
          title: const CustomText(
            'Back',
            textStyle: TextStyles.textSmall,
            textAlign: TextAlign.start,
          ),
          titleSpacing: 5,
          leading: GestureDetector(
            onTap: () => Get.back(),
            child: const Icon(
              Icons.arrow_back,
              color: Color(ColorCode.darkGrey),
              size: 35,
            ),
          ),
        ),
        body: Container(
          padding: const EdgeInsets.symmetric(horizontal: 60),
          color: const Color(ColorCode.primaryBackground),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              CustomText(
                'Player name',
                textStyle: TextStyles.textMedium.copyWith(
                  color: const Color(ColorCode.lightGrey),
                  fontFamily: 'CoconPro',
                ),
              ),
              const SizedBox(
                height: 100,
              ),
              ObxValue<RxBool>((goPlaying) {
                return Stack(
                  clipBehavior: Clip.none,
                  alignment: Alignment.topCenter,
                  fit: StackFit.loose,
                  children: <Widget>[
                    Container(
                      padding:
                          const EdgeInsets.only(right: 45, left: 45, top: 50),
                      height: 229,
                      decoration: BoxDecoration(
                        color: const Color(ColorCode.black),
                        borderRadius: BorderRadius.circular(5.0),
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              Expanded(
                                child: CustomTextField(
                                  hintText: 'Type your Name',
                                  controller: controller.playerNameController,
                                  keyboardType: TextInputType.text,
                                  fontStyle: TextStyles.textSmall.copyWith(
                                    fontFamily: 'CoconPro',
                                    color: Colors.white,
                                    fontWeight: FontWeight.w300,
                                  ),
                                ),
                              ),
                              const SizedBox(
                                width: 15,
                              ),
                              Container(
                                width: 100,
                                child: CustomTextField(
                                  hintText: '',
                                  controller:
                                      controller.autoGeneratedNumberController,
                                  keyboardType: TextInputType.text,
                                  fontStyle: TextStyles.textSmall.copyWith(
                                    fontFamily: 'CoconPro',
                                    color: Colors.white,
                                    fontWeight: FontWeight.w300,
                                  ),
                                  isEnabled: false,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(
                            height: 20,
                          ),
                          CustomText(
                            goPlaying.value
                                ? 'Up to 9 characters '
                                : 'Playerame will appear on the leaderboard, allowing you to follow your score.',
                            textStyle: TextStyles.textXSmall.copyWith(
                              color: const Color(ColorCode.lightGrey3),
                            ),
                            textAlign: TextAlign.start,
                          )
                        ],
                      ),
                    ),
                    Positioned(
                      bottom: 160,
                      child: Image.asset('assets/images/single_play.png',
                          color: goPlaying.value
                              ? null
                              : const Color(ColorCode.grey),
                          height: 165,
                          width: 171),
                    ),
                    Positioned(
                      top: 140,
                      left: 270,
                      child: GestureDetector(
                        onTap: () => {
                          if (goPlaying.value)
                            controller.createTicket()
                        },
                        child: Stack(
                          alignment: Alignment.center,
                          children: [
                            Image.asset(
                                goPlaying.value
                                    ? 'assets/images/go_button_active_bg.png'
                                    : 'assets/images/go_button_inactive_bg.png',
                                height: 165,
                                width: 171),
                            CustomText(
                              'Go',
                              textStyle: TextStyles.textXLarge.copyWith(
                                fontFamily: 'CoconPro',
                                color: Color(
                                  goPlaying.value
                                      ? ColorCode.aqua
                                      : ColorCode.lightGrey2,
                                ),
                              ),
                            )
                          ],
                        ),
                      ),
                    ),
                  ],
                );
              }, controller.goPlaying)
            ],
          ),
        ),
      ),
    );
  }
}
