// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG2Jxyl1PlQbe4S3IvNlo7cNbPAZmSPJ8',
    appId: '1:843733599056:web:70f4909b687d5f3577e255',
    messagingSenderId: '843733599056',
    projectId: 'spacejumpevreux-4820c',
    authDomain: 'spacejumpevreux-4820c.firebaseapp.com',
    databaseURL: 'https://spacejumpevreux-4820c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacejumpevreux-4820c.appspot.com',
    measurementId: 'G-786QZ0CP7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqAte8mr6VlaLRgB96pgFLslaVpaFhxg8',
    appId: '1:843733599056:android:5d4fb995376a94cb77e255',
    messagingSenderId: '843733599056',
    projectId: 'spacejumpevreux-4820c',
    databaseURL: 'https://spacejumpevreux-4820c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacejumpevreux-4820c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2CY_MUVJAYY6K08GSKwv80A6VXiFWxgE',
    appId: '1:843733599056:ios:d3fa6293b0b314a977e255',
    messagingSenderId: '843733599056',
    projectId: 'spacejumpevreux-4820c',
    databaseURL: 'https://spacejumpevreux-4820c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spacejumpevreux-4820c.appspot.com',
    iosClientId: '843733599056-djc5lrhefpfjlq96iv68mk3i21ilqlp6.apps.googleusercontent.com',
    iosBundleId: 'com.pleyo.tablet',
  );
}
