// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwyMLztluPfdCM6CvwK316sY335A3uX8Y',
    appId: '1:525581989538:web:7340cfe4d1cb3b247249fb',
    messagingSenderId: '525581989538',
    projectId: 'playo-c1060',
    authDomain: 'playo-c1060.firebaseapp.com',
    storageBucket: 'playo-c1060.appspot.com',
    measurementId: 'G-YD9R4NNVXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMVU_wiJ5Nc_irBicPN7qRM60sE6sO0NI',
    appId: '1:525581989538:android:685f4d98e3fe50bc7249fb',
    messagingSenderId: '525581989538',
    projectId: 'playo-c1060',
    storageBucket: 'playo-c1060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy_HDA8Nw3JxrDujEgGa_pfzkXVaNRbV8',
    appId: '1:525581989538:ios:d09b04c63215462a7249fb',
    messagingSenderId: '525581989538',
    projectId: 'playo-c1060',
    storageBucket: 'playo-c1060.appspot.com',
    iosClientId: '525581989538-b3o399r9vg390g0n2m1of24b7fjeg18h.apps.googleusercontent.com',
    iosBundleId: 'com.pleyo.pos',
  );
}
